### ISSUE TITLE
Fullwidth right parenthesis "）" does not rotate after Kana in vertical writing mode in Chrome

### ISSUE THREAD

**Issue by mgeorgetw** [adobe-fonts/source-han-serif#72]
I was trying vertical layout on the web and found fullwidth right parenthesis "）" does not rotate when following a Kana. (See image below) However, this happens only in Google Chrome and only when my CSS is
```css
article { font-family: "Source Han Serif TC" }
```
Tried CN, JP, TW, they all worked fine in Chrome. Even when specifically setting the font family as the following worked fine.
```css
article { font-family: "Source Han Serif TC Regular" }
```
Not sure where the problem might be. Hope this issue is relevant.

![screenshot 2017-11-17 12 25 18](https://user-images.githubusercontent.com/25784056/32930493-02450762-cb9a-11e7-80f7-aae335e5133f.png)
